#!/usr/bin/env bash

memory=$(( 800 * 8 )) # Convert from MegaWords to MegaBytes


# All parameters can be accessed here as well
echo "Submitting job that uses the following correlation method: cic"

qmolpro -n 1 -m ${memory}M -t 5:00 -d 50 base_cc-pVTZ_second_rhf_cic.inp
