name: Run tests

on: [push, pull_request]

jobs:
    test:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3
              uses: actions/setup-python@v2
              with:
                  python-version: '3.x'
            - name: Run tests
              run: python3 run_tests.py
              shell: bash
